# Generated by Django 6.0.2 on 2026-03-01 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du Client')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse Principale')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Langue préférée')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Chauffeur')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Désignation')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix de base')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Guide')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('languages', models.CharField(help_text='Ex: Anglais, Espagnol, Français', max_length=200, verbose_name='Langues parlées')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name="Nom de l'Agence")),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modèle')),
                ('capacity', models.IntegerField(default=17, verbose_name='Capacité')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Heure')),
                ('num_people', models.IntegerField(default=1, verbose_name='Nombre de personnes')),
                ('language', models.CharField(choices=[('FR', 'Français'), ('EN', 'Anglais'), ('ES', 'Espagnol'), ('IT', 'Italien'), ('AR', 'Arabe'), ('DE', 'Allemand'), ('PT', 'Portugais'), ('ZH', 'Chinois'), ('JA', 'Japonais'), ('RU', 'Russe'), ('NL', 'Néerlandais'), ('TR', 'Turc'), ('KO', 'Coréen')], default='FR', max_length=2, verbose_name='Langue de la prestation')),
                ('pickup_address', models.CharField(help_text='Ex: Hotel Rembrandt, Kasbah Rose', max_length=255, verbose_name='Adresse / Lieu de ramassage')),
                ('pickup_location_detail', models.CharField(blank=True, help_text='Ex: Porte principale, Réception, Devant le café', max_length=255, null=True, verbose_name='Localisation de la prise en charge')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='authentication.client', verbose_name='Client')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='authentication.driver', verbose_name='Chauffeur')),
                ('excursion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.excursion', verbose_name='Excursion')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='authentication.guide', verbose_name='Guide')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.provider', verbose_name='Agence')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='authentication.vehicle', verbose_name='Véhicule')),
            ],
        ),
    ]
