# Generated by Django 6.0.2 on 2026-03-08 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_client_driver_excursion_guide_provider_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('datos_eliminados', models.JSONField()),
                ('datos_legibles', models.TextField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_eliminacion'],
            },
        ),
    ]
