# Generated by Django 6.0.2 on 2026-03-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_historialeliminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='authentication.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='authentication.driver', verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='excursion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.excursion', verbose_name='Excursion'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='authentication.guide', verbose_name='Guide'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.provider', verbose_name='Agence'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='authentication.vehicle', verbose_name='Véhicule'),
        ),
    ]
