# Generated by Django 6.0.2 on 2026-03-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_booking_client_alter_booking_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialeliminacion',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
