# Generated by Django 6.0.2 on 2026-03-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_historialeliminacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.excursion', verbose_name='Excursion associée'),
        ),
    ]
