# Generated by Django 6.0.2 on 2026-03-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_client_excursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom del Lieu (Hôtel/Point)')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse')),
                ('pickup_instructions', models.TextField(blank=True, help_text='Ex: Attendre devant la porte principale', null=True, verbose_name='Instructions de prise en charge')),
                ('gps_coordinates', models.CharField(blank=True, help_text='Ex: 35.7642, -5.8184', max_length=100, null=True, verbose_name='Coordonnées GPS')),
            ],
            options={
                'verbose_name': 'Lieu de prise en charge',
                'verbose_name_plural': 'Lieux de prise en charge',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_location_detail',
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location_details',
            field=models.ForeignKey(blank=True, help_text='Ex: Porte principale, Réception, Devant le café', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='authentication.location', verbose_name='Localisation de la prise en charge'),
        ),
    ]
