# Generated by Django 6.0.2 on 2026-03-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_location_remove_booking_pickup_location_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'adresse (Ex: Maison, Bureau)")),
                ('full_address', models.TextField(verbose_name='Adresse complète')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Postal')),
            ],
            options={
                'verbose_name': 'Adresse du Client',
                'verbose_name_plural': 'Adresses des Clients',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='client_address_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='authentication.clientaddress', verbose_name='Adresse Principale'),
        ),
    ]
