# Generated by Django 6.0.2 on 2026-03-14 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_clientaddress_remove_client_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='authentication.provider', verbose_name='Fournisseur / Agence'),
        ),
    ]
